### ISSUE TITLE
Support `environment` syntax and add `--environment` option

### ISSUE THREAD

**Issue by ybiquitous** [wata727/elastic_whenever#47]
Hi, thanks for the very nice gem.

I'd like to use the `environment` syntax on a configuration file instead of the `@environment` instance variable.

Because:

- Referring to instance variables feel weird to some people.
- It seems hard to find a relationship between a CLI option (e.g. `--set 'environment=staging'`) and `@environment` in a configuration file.

So, I suggest as follow:

1. Can access to a new `environment` syntax:

```diff
-if @environment == 'production'
+if environment == 'production'
   every :day, at: '03:00am' do
     runner 'Hoge.run'
   end
 end
```

2. Add a new `--environment` CLI option (default: `production`) instead of `--set 'environment=...'`.

```diff
-elastic_whenever --set 'environment=staging'
+elastic_whenever --environment=staging
```

What do you think about this suggestion?
It would be great if you could consider this. Thanks.

**Comment by wata727** [comment]
Umm, it seems at first glance to make sense. However, `environment` is not a special value for Whenever (Elastic Whenever). When supporting this, we will also need to support various settings that are used by other users as well.

I'm not sure why Whenever adopted the `--set` option, but I think it's probably to allow the user to set the value freely. As long as Elastic Whenever claims compatibility with Whenever, I think it should be followed.

**Comment by ybiquitous** [comment]
> When supporting this, we will also need to support various settings that are used by other users as well.

Surely.
Then, what do you think about the usage of instance variables?

**Comment by wata727** [comment]
I have no opinion, but if Whenever users are using it, Elastic Whenever also supports it.

**Comment by ybiquitous** [comment]
I'm unfamiliar with Whenever, so I tried finding its document describing the `--env` option. Here is the document:

https://github.com/javan/whenever/wiki/Setting-variables-on-the-fly

Also, some default values (e.g. `production`) are described on the README:

https://github.com/javan/whenever#define-your-own-job-types

The document above describes the usage of instance variables, so I think it reasonable that elastic_whenever also supports them, as you say. 👍 

So, I have a simple suggestion. To help people unfamiliar with Whenever (like me), how about adding a description about the usage of the `--set` option and instance variables (for example on the README)?
(Of course, it seems enough to me even if a brief description and a link to the Whenever document.)

It seems better if descriptions about the following default values would be added.

https://github.com/wata727/elastic_whenever/blob/2fa8f51c259d83d99ce734872d8d7b1700917136/lib/elastic_whenever/schedule.rb#L51
https://github.com/wata727/elastic_whenever/blob/2fa8f51c259d83d99ce734872d8d7b1700917136/lib/elastic_whenever/schedule.rb#L55

I think that people could continue to use the gem with confidence if significant options or behaviors would be documented.

**Comment by wata727** [comment]
I'd be happy to add it to the README if a user wanted, but I'm worried that we will eventually add all the Whenever's documentation.

**Comment by wata727** [comment]
By the way, Bundler's behavior is described here https://github.com/wata727/elastic_whenever#bundle-commands

**Comment by ybiquitous** [comment]
At least I want a description about `--set` option. It would be enough if there would be a brief one and a link to the Whenever doc.

Can I try to write it if you could allow?

**Comment by wata727** [comment]
> Can I try to write it if you could allow?

Sure!
